name: GrapplingHook
version: 1.0.0
main: provanasservices.grapplinghook.Main
api-version: 1.16
description: grappling hook plugin
author:  _KatilCivciv_
commands:
  getgrapplinghook:
    description: Get grappling hook.
    usage: /<command>
    permission: op
  grapplinghookreload:
    description: Reload config.
    usage: /<command>
    permission: op