grapplinghook:
  prefix: "§7[§9Grappling Hook§7] "
  #Plugin prefix
  CooldownTime: 3
  #Cooldown Time. Default: 3
  cooldowntext: "§4You cant use this item for another %timer% seconds!!"
  #In cooldown text. Default: "§4You cant use this item for another %timer% seconds!!"
  nopermtext: "§cYou don't have permission!"
  #No perm text
  #permission: use.hook
  velocity:
    air:
      #grappling hook settings when hook on air
      onairvelocity: 3
      #Set speed when hook on air. Default: 3
      onairsety: 1
      #Set y direction speed when hook on air. Default: 1
    land:
      #grappling hook settings when hook on land
      onlandvelocity: 0.4
      #Set speed when hook on land. Default: 0.4
      onlandchangeadd:
        #Changing last location.Y is a double number, others integer. Default: x: 0 , y: 2.6 , z: 0
        x: 0
        y: 2.6
        z: 0